---
- name: per user
  block:
    - set_fact:
        my_user: "{{ item }}"

    - name: get auth token from keycloak codeready realm
      uri:
        url: http://keycloak-codeready.{{ route_subdomain }}/auth/realms/codeready/protocol/openid-connect/token
        method: POST
        body: "username={{ my_user }}&password=openshift&grant_type=password&client_id=admin-cli"
        status_code: 200
        headers:
          Content-Type: "application/x-www-form-urlencoded"
      register: user_access_token_result

    - set_fact:
        user_access_token_bearer: "{{ user_access_token_result.json | json_query('access_token') }}"

    - name: Install factory from json content
      uri:
        url: http://codeready-codeready.{{ route_subdomain }}/api/factory
        method: POST
        body: "{{ lookup( 'template', 'codeready-factory.json.j2' ) }}"
        body_format: json
        status_code: 200,201
        headers:
          Authorization: "Bearer {{ user_access_token_bearer }}"
      vars:
        username: "{{ my_user }}"
        password: "openshift"
