---
# add keycloak realm
- name: Get SSO username
  shell: |
    oc get deployment keycloak -n '{{ codeready_project }}' -o=jsonpath={'.spec.template.spec.containers[0].env[?(@.name=="SSO_ADMIN_USERNAME")].value'}
  register: sso_admin_username

- name: Get SSO password
  shell: |
    oc get deployment keycloak -n '{{ codeready_project }}'  -o=jsonpath={'.spec.template.spec.containers[0].env[?(@.name=="SSO_ADMIN_PASSWORD")].value'}
  register: sso_admin_password

- name: extract route_subdomain
  k8s_facts:
    kind: Ingress
  register: route_subdomain_r

- set_fact:
    route_subdomain: "{{ route_subdomain_r.resources[0].spec.domain | trim }}"

- name: Get SSO admin token
  uri:
    url: http://keycloak-codeready.{{ route_subdomain }}/auth/realms/master/protocol/openid-connect/token
    method: POST
    body_format: form-urlencoded
    body: "username={{ sso_admin_username.stdout }}&password={{ sso_admin_password.stdout }}&grant_type=password&client_id=admin-cli"
    status_code: 200,201,204
  register: sso_admin_token

- set_fact:
    master_access_token_bearer: "{{ sso_admin_token.json | json_query('access_token') }}"

- name: Print SSO connection info
  debug:
    msg: "url: http://keycloak-codeready.{{ route_subdomain }} username: {{ sso_admin_username.stdout }} password: {{ sso_admin_password.stdout }}"

- name: pre-create {{ codeready_generate_user_count }} users in codeready realm with format (user%d)
  uri:
    url: http://keycloak-codeready.{{ route_subdomain }}/auth/admin/realms/codeready/users
    method: POST
    body: "{{ lookup('template','codeready-user.json.j2') }}"
    body_format: json
    status_code: 201,409
    headers:
      Authorization: "Bearer {{ master_access_token_bearer }}"
      Content-Type: "application/json"
  vars:
    username: "{{ item }}"
  with_sequence: start={{ codeready_generate_user_count|int if codeready_generate_user_count|int < 1 else 1}} end={{ codeready_generate_user_count }} format=user%d
  when: codeready_generate_user_count|int > 0

- name: add factory to users
  include_tasks: add_factory_multi.yml
  with_sequence: start={{ codeready_generate_user_count|int if codeready_generate_user_count|int < 1 else 1}} end={{ codeready_generate_user_count }} format=user%d
  when:
    - codeready_generate_user_count|int > 0
