---
- name: BUG in Camel K, need to delete CSC in user{{ item }} namespace
  k8s:
    state: absent
    api_version: operators.coreos.com/v1
    kind: CatalogSourceConfig
    name: installed-community-openshift-operators-user{{ item }}
    namespace: openshift-marketplace

- name: BUG in Camel K, need to unsubscribe Camel in {{ item }} namespace
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: camel-k
    namespace: '{{ item }}'

- name: Delete {{ item }} for admin in {{ item }}
  k8s:
    state: absent
    api_version: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    name: '{{ item }}-admin-{{ item }}-namespace'
    namespace: '{{ item }}'
    
- name: Delete {{ item }} for view in {{ kafka_earth_namespace }}
  k8s:
    state: absent
    api_version: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    name: '{{ item }}-view-{{ kafka_earth_namespace }}-namespace'
    namespace: '{{ item }}'

- name: Delete {{ item }} for view in {{ db_earth_namespace }}
  k8s:
    state: absent
    api_version: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    name: '{{ item }}-view-{{ db_earth_namespace }}-namespace'
    namespace: '{{ item }}'

- name: Delete {{ item }} Namespace
  k8s:
    state: absent
    kind: Namespace
    name: '{{ item }}'
