---
- name: Process user namespace
  k8s:
    api_version: v1
    kind: Namespace
    name: 'user{{ item }}'
    state: present

- name: Give user{{ item }} access to projects
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'user-rolebinding.yaml.j2') }}"
  loop:
    - { user: 'user{{ item }}', namespace: 'user{{ item }}', role: 'admin' }
    - { user: 'user{{ item }}', namespace: '{{ kafka_earth_namespace }}', role: 'view' }
    - { user: 'user{{ item }}', namespace: '{{ db_earth_namespace }}', role: 'view' }
  loop_control:
    loop_var: item_project

- name: Lazy Christina just wants to install this web app for now TBC
  shell: oc new-app weimeilin/dilii-ui:latest -n 'user{{ item }}'

- name: Lazy Christina just want to exposed UI route for now TBC
  shell: oc expose service dilii-ui -n 'user{{ item }}'
