---
- name: Delete CustomResourceDefinitions
  k8s:
    state: absent
    api_version: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    name: '{{ item }}'
  loop:
    - "webapps.integreatly.org"

- name: Delete OAuthClient
  k8s:
    state: absent
    api_version: v1
    kind: OAuthClient
    name: tutorial-web-app

- name: Delete Role
  k8s:
    state: absent
    api_version: rbac.authorization.k8s.io/v1beta1
    kind: Role
    name: tutorial-web-app-operator