- name: Define User Fuse Name
  set_fact: 
    user_fuse_project: '{{ fuse_project }}-user{{ item }}'
    
- name: Wait for Syndesis operator to install
  k8s_facts:
      api_version: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      name: 'fuse-online-operator.v{{ fuse_version }}'
      namespace: '{{ user_fuse_project }}'
  register: csv_status
  until: (csv_status.resources is defined) and (csv_status.resources|length>0) and (csv_status.resources[0].status.phase == 'Succeeded')
  retries: 10
  delay: 30

- name: Evaluate Syndesis Cluster
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'fuse-cluster.yaml.j2') }}"

- name: extract route_subdomain
  k8s_facts:
    kind: Ingress
  register: route_subdomain_r
  
- set_fact:
    route_subdomain: "{{ route_subdomain_r.resources[0].spec.domain | trim }}"

