---
- name: Delete Subscription
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: amq-streams
    namespace: '{{ operators_project }}'

- name: Delete CatalogSourceConfig
  k8s:
    state: absent
    api_version: operators.coreos.com/v1
    kind: CatalogSourceConfig
    name: messaging-streams
    namespace: openshift-marketplace

- name: Collect CustomResourceDefintions
  k8s_facts:
    api_version: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    label_selectors:
    - app=strimzi
  register: crds_list

# - debug: var=crds_list

- name: Delete CustomResourceDefinitions
  k8s:
    state: absent
    api_version: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    name: '{{ item.metadata.name }}'
  loop: '{{ crds_list.resources }}'