---
- name: Evaluate {{ operators_project }} namespace if not exists 
  k8s:
    api_version: v1
    kind: Namespace
    name: '{{ operators_project }}'
    state: present

- name: Evaluate Operator Group
  k8s:
    api_version: operators.coreos.com/v1alpha2
    kind: OperatorGroup
    name: workshop-operators
    namespace: '{{ operators_project }}'

- name: Evaluate Online OperatorSource
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'online-opsrc.yaml.j2') }}"

- name: Evaluate Online CatalogSourceConfig
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'online-csc.yaml.j2') }}"

- name: Evaluate Online Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'online-subscription.yaml.j2') }}"

