---
- name: Evaluate {{ che_project }} namespace if not exists 
  k8s:
    api_version: v1
    kind: Namespace
    name: '{{ che_project }}'
    state: present

- name: Evaluate Eclipse Che CatalogSourceConfig
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'che-csc.yaml.j2') }}"

- name: Evaluate Eclipse Che Operator Group
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'che-operatorgroup.yaml.j2') }}"

- name: Evaluate Eclipse Che Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'che-subscriptionyaml.j2') }}"

- name: Wait for Che operator to install
  k8s_facts:
      api_version: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      name: 'eclipse-che.v{{ che_version }}'
      namespace: '{{ che_project }}'
  register: csv_status
  until: (csv_status.resources is defined) and (csv_status.resources|length>0) and (csv_status.resources[0].status.phase == 'Succeeded')
  retries: 10
  delay: 30

- name: Evaluate Eclipse Che Cluster
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'che-cluster.yaml.j2') }}"

- name: extract route_subdomain
  k8s_facts:
    kind: Ingress
  register: route_subdomain_r
  
- set_fact:
    route_subdomain: "{{ route_subdomain_r.resources[0].spec.domain | trim }}"

- name: Wait for codeready to be running
  uri:
    url: http://che-{{ che_project }}.{{ route_subdomain }}/api/system/state
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 30

