---
- name: Create Earth Kafka Namespace
  k8s:
    api_version: v1
    kind: Namespace
    name: '{{ kafka_earth_namespace }}'
    state: present

- name: Create Earth Kafka Cluster
  k8s:
    state: present
    namespace: '{{ kafka_earth_namespace }}'
    resource_definition: "{{ lookup('template', 'kafka-earth.yaml.j2') }}"

- name: Create Earth Database Namespace
  k8s:
    api_version: v1
    kind: Namespace
    name: '{{ db_earth_namespace }}'
    state: present

- name: Enable anyuid on Earth Database Namespace
  shell: "oc adm policy add-scc-to-user anyuid -z default -n {{ db_earth_namespace }}"

- name: Deploy Earth Database
  shell: "oc new-app {{ mssqlserver_image }}:{{ mssqlserver_version }} \
            -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password!' \
            -e 'MSSQL_PID=Standard' -e 'MSSQL_AGENT_ENABLED=true' \
            -n {{ db_earth_namespace }}"